### ISSUE TITLE
[Bug] Does not work at all, wrong import statement for cjs library picocolor

### ISSUE THREAD

**Issue by MajPay** [Mister-Hope/gulp5-sass-plugin#861]
**Describe the bug**
The basic example (see below) does not work. Picocolor can not be imported form the gulp-5-sass-plugin index.js file

> SyntaxError: Named export 'underline' not found. The requested module 'picocolors' is a CommonJS module, which may not support all module.exports as named exports.
> CommonJS modules can always be imported via the default export, for example using:
> 
> import pkg from 'picocolors';

You should change the import statement i guess

**Comment by aredridel** [comment]
Yeah, same here. Probably works when transpiled as in testing, but not with the native node loader.

**Comment by Mister-Hope** [comment]
Fixed in v2.0.4
